project:
  type: book
  output-dir: docs

book:
  title: "DATA 3230 - Data Visualization"
  author: "Dr Austin R Brown"
  date: "Fall 2024"
  chapters:
    - index.qmd
    - intro.qmd
    - communicating_data.qmd
    - how_much.qmd
    - legends_colors_fonts.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

execute: 
  echo: true
  include: true
  warning: false
  message: false
  tidy: false

