# Preface {.unnumbered}

Welcome to [**DATA 3230 - Data Visualization**]{.underline}! My name is Dr Austin Brown and I am a faculty member in the School of Data Science and Analytics at Kennesaw State University.

This course is designed to teach students not only how to create data visualizations, but how to create them in an appropriate and aesthetically pleasing manner.

# Coding Requirements

In this course, I use R programming and specifically elements of the `tidyverse` to teach students how to generate beautiful visualizations using the popular visualization package, `ggplot2`. Now, you may be asking yourself: ***"what if I don't have experience with R programming? Can I still be successful?"***

The answer is unequivocally, yes! We start from the basics and work our way up to more complex examples, making sure that you have all the relevant code and explanations you need to be successful in this class and beyond.

All I ask is that along the way, if you run into issues, be sure to ask for help! That's what I'm here for!

So if you're ready to learn how to tell stories with data through a visual medium, come along with me!

# References

Some of the content I use to teach this course comes from:

1.  [Communicating Data with Tableau](https://www.oreilly.com/library/view/communicating-data-with/9781449372019/) by Ben Jones
2.  [R for Data Science 2nd Edition](https://r4ds.hadley.nz/) by Hadley Wickham, Mine Cetinkaya-Rundel, and Garrett Grolemund
3.  [R Graphics Cookbook 2nd Edition](https://r-graphics.org/) by Winston Chang

# Accessing Content

All of the content for the course, including code and datasets, can be found at my [GitHub repo](https://github.com/abrown9008/DATA-3230-Data-Visualization) for this course.
